package com.m0e_n00b.viriviri

import android.content.Context
import java.io.BufferedReader

/**
 * Offline, frequency-ordered pinyin lexicon bundled from the rime-ice dictionary
 * (https://github.com/iDvel/rime-ice, GPL-3.0-or-later; single-char frequency from the
 * BLCU 250M-character corpus). The asset is a compact, pruned table generated by
 * scripts/generate-pinyin-lexicon.ps1 with two record types per line:
 *
 *   P<TAB>compactpinyin<TAB>word:weight            (best high-frequency word for that pinyin)
 *   C<TAB>syllable<TAB>char:weight,char:weight,... (frequency-ordered chars for a syllable)
 *
 * Lookup priority: exact word -> word-prefix completion (typing 'ces' surfaces 测试) ->
 * single-syllable chars -> single-letter/partial aggregation across syllables -> ICU fallback.
 */
object BundledPinyinData {
  const val ASSET_PATH = "ime/pinyin_lexicon.txt"

  /** Parses the bundled table text. Exposed so a JVM test can feed an inline string. */
  fun parse(lines: Sequence<String>): PinyinTable {
    val phrases = HashMap<String, String>()
    val syllableChars = HashMap<String, List<String>>()
    val syllableWeights = HashMap<String, Map<String, Long>>()
    for (raw in lines) {
      val line = raw.trim()
      if (line.isEmpty() || line.startsWith("#")) continue
      val parts = line.split('\t')
      if (parts.size < 3) continue
      when (parts[0]) {
        "P" -> {
          val head = parts[2].substringBefore(':')
          if (head.isNotEmpty()) phrases.putIfAbsent(parts[1], head)
        }
        "C" -> {
          val weighted = LinkedHashMap<String, Long>()
          val ordered = ArrayList<String>()
          parts[2].split(',').forEach { token ->
            val ch = token.substringBefore(':')
            if (ch.isNotEmpty()) {
              val w = token.substringAfter(':', "").toLongOrNull() ?: 0L
              if (!weighted.containsKey(ch)) {
                weighted[ch] = w
                ordered.add(ch)
              }
            }
          }
          if (ordered.isNotEmpty()) {
            syllableChars[parts[1]] = ordered
            syllableWeights[parts[1]] = weighted
          }
        }
      }
    }
    return PinyinTable(phrases, syllableChars, syllableWeights)
  }

  fun loadFromAssets(context: Context): PinyinTable =
      context.assets.open(ASSET_PATH).bufferedReader().use { reader ->
        parse(reader.lineSequence())
      }
}

/** Immutable parsed lexicon: compact-pinyin -> word, and syllable -> frequency-ordered chars. */
class PinyinTable(
    val phrases: Map<String, String>,
    val syllableChars: Map<String, List<String>>,
    /** Per-syllable character -> corpus frequency weight (higher = more common). */
    val syllableWeights: Map<String, Map<String, Long>> = emptyMap(),
) {
  /** Exact best word for a fully-typed compact pinyin, e.g. ceshi -> 测试. */
  fun exactWord(compactPinyin: String): String? = phrases[compactPinyin]

  /**
   * Best word whose compact pinyin continues what the user has typed, e.g. typing "ces"
   * completes to 测试 (ceshi). The typed prefix must be a valid syllable prefix: it splits
   * into whole known syllables, optionally followed by a short in-progress syllable. This
   * rejects letter-only matches that cross a syllable boundary (e.g. "ce" matching a
   * "ceng..." word) and requires at least one complete syllable so a bare letter like "c"
   * does not steal the suggestion away from single-character aggregation.
   */
  fun prefixWord(prefix: String, isSyllable: (String) -> Boolean): String? {
    if (prefix.isEmpty()) return null
    if (!isValidSyllablePrefix(prefix, isSyllable)) return null
    var bestKey: String? = null
    for (key in phrases.keys) {
      if (key.length <= prefix.length || !key.startsWith(prefix)) continue
      if (bestKey == null || key.length < bestKey!!.length) bestKey = key
    }
    return bestKey?.let { phrases[it] }
  }

  private fun isValidSyllablePrefix(prefix: String, isSyllable: (String) -> Boolean): Boolean {
    var index = 0
    var wholeSyllables = 0
    while (index < prefix.length) {
      var matched = -1
      val maxLen = minOf(MAX_SYLLABLE_LEN, prefix.length - index)
      for (len in maxLen downTo 1) {
        if (isSyllable(prefix.substring(index, index + len))) {
          matched = index + len
          break
        }
      }
      if (matched < 0) break
      index = matched
      wholeSyllables++
    }
    val remainder = prefix.length - index
    return wholeSyllables >= 1 && remainder in 0..2
  }

  private companion object {
    const val MAX_SYLLABLE_LEN = 6
  }
}
